version: '3.7'

services:
  clickhouse:
    image: bitnami/clickhouse:latest
    env_file:
      - .env.docker
    ports:
      - "9999:9000"
      - "8123:8123"
    volumes:
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
  sniffer:
    build: .
    env_file:
      - .env.docker
    ports:
      - "8888:8888"
    depends_on:
      - clickhouse
    restart: on-failure